version: '2'
services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/src/app
        environment:
            NODE_ENV: production
        links:
            - db

