db:
    image: postgres
    environment:
        POSTGRES_DB: dbTodos
    ports:
        - "5432:5432"
web:
    build: .
    ports:
        - "8000:8000"
    environment:
        NODE_ENV: production
    links:
        - db


